apiVersion: v1
kind: Service
metadata:
  name: service-demo
spec:
  selector:
    project: roboshop
    env: development
    component: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
