apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels: 
    project: roboshop
    env: development
    component: frontend
    purpose: service-nodeport
spec: 
  containers:
  - name: nginx
    image: nginx
