apiVersion: v1
kind: Service
metadata:
  name: service-lb 
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    env: development
    component: frontend
    purpose: service-lb
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
    nodePort: 30007 